### ISSUE TITLE
Some Improvement Ideas

### ISSUE THREAD

**Issue by whipowill** [panthernet/D2RSO#1]
Can you add an option for the icons to align to the right instead of the left?

Can you add an option to hide the numbers until the range gets within a number of seconds that I choose?  So no numbers until it's 10 seconds, for example.  Or it says something like 2m, 1m, and then counts from 1m.  Or an option to hide numbers entirely and it turns red when there are 10 seconds left.

A Minor issue is when I click to move where the icons will show on the screen it hides the game and shows me Windows.  I'm using this on D2LOD.

The standalone install didn't work, but the .NET install did.  Great work on this, very cool idea.

EDIT:  If you made a version of this that could read memory and add buffs and debuffs, it would be epic.

**Comment by panthernet** [comment]
Hi, thanks for feedback. I will look into your suggestions.

For the D2 hide bug, is it runs in fullscreen? And what OS version do you have? Overlay should be completely invisible for clicks

**Comment by whipowill** [comment]
It's the "positioning" option, when I have that on and I'm in the game, and I click to drag and move it, it kicks me back out to Windows.  I'm on Windows 10 playing D2LOD fullscreen, but it might be "windowed" fullscreen.  I'm using D2DX as the video library.

**Comment by panthernet** [comment]
Yeah, unfortunately the drag window won't work well in fullscreen mode because it belongs to another process (not the game). So you have to adjust it with several tries.

**Comment by panthernet** [comment]
Released v1.0.1 with some ideas implemented (as I can). The debuff tracking would be cool feature but unfortunately is unavailable right now.
