### ISSUE TITLE
Ap randomly crashes

### ISSUE THREAD

**Issue by badjer2** [panthernet/D2RSO#10]
app randomly crashes/shuts down. dont see a log file

and id want to add another suggestion, ad a sound on timer red or expire

event viewer says this:
Fault bucket 1622676063515337827, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: D2RSO.exe
P2: 1.0.0.0
P3: 62577b55
P4: coreclr.dll
P5: 5.0.1722.21314
P6: 62577019
P7: c0000005
P8: 00000000001b2ce9
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERF055.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERF2F5.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERF316.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERF314.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERF353.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_D2RSO.exe_684c8a30dfbdd327b87367e214f1b28be9c496_c1ca54fb_5c439234-610d-43fa-b497-278d8389d2c7

Analysis symbol: 
Rechecking for solution: 0
Report Id: f53ffb1d-e4f9-40fd-b946-3fd0247c522e
Report Status: 268435456
Hashed bucket: 8e3c745d60cee3e89684e7484f5c6463
Cab Guid: 0

Application: D2RSO.exe
CoreCLR Version: 5.0.1722.21314
.NET Version: 5.0.17
Description: The process was terminated due to an internal error in the .NET Runtime at IP 00007FFEA09B2CE9 (00007FFEA0800000) with exit code c0000005.

Faulting application name: D2RSO.exe, version: 1.0.0.0, time stamp: 0x62577b55
Faulting module name: coreclr.dll, version: 5.0.1722.21314, time stamp: 0x62577019
Exception code: 0xc0000005
Fault offset: 0x00000000001b2ce9
Faulting process id: 0x5a2c
Faulting application start time: 0x01d8d09658e07d48
Faulting application path: D:\Seeker\Desktop\New folder (2)\D2RSO.exe
Faulting module path: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.17\coreclr.dll
Report Id: f53ffb1d-e4f9-40fd-b946-3fd0247c522e
Faulting package full name: 
Faulting package-relative application ID:

**Comment by badjer2** [comment]
old version crashes, but much less than the new (mouse 4&5 version)

**Comment by panthernet** [comment]
Thanks, will check it

**Comment by badjer2** [comment]
Can you replicate the crashes? can i provide any additional info to help?
previous version is moreor less stable, but im unable to use new one bc  of crashes, could be a conflict with my system?

**Comment by panthernet** [comment]
[D2RSO-v1.0.5pre-windows.zip](https://github.com/panthernet/D2RSO/files/9657560/D2RSO-v1.0.5pre-windows.zip)
Hi, please check this version. I've added some flow control and logging. Let me know if it still crashes and if so check the log file at  `C:\Users\USERNAME\AppData\Local\D2RSO`

I don't have crashes on my side btw.

**Comment by badjer2** [comment]
it crashes 100% when i ctrl click on items to move from invetrory to stash and other way around
hen it crashes mouse becomes glitchy for couple secs like proc is overburdened
there is no log file just json in there

**Comment by ghost** [comment]
I have the same problem. It works fine if I have both Select Key and Skill Key set. But if I only have Skill Key set, it crashes as soon as I change to another active window, no error or anything. I've tried the 1.0.5pre version, but in this version, if I dont add any Select Key, it just doesn't work.

Using the Default profile fixed it in 1.0.5pre, now it works without crashing. But if I create another profile it doesn't work at all.

**Comment by panthernet** [comment]
I'm sorry, the 3rd party keylogger is trash. I was too lazy to make it better. Probably I've found the issue and will upload new version soon. Have to check  some stuff atm.

**Comment by panthernet** [comment]
@badjer2 @thegreatgoose new version is up, let me know if it works

**Comment by ghost** [comment]
Everything seems to work for me now. 👍

**Comment by badjer2** [comment]
not crashing anymore
you are missing right click (i think it should be mouse2)
and red icon should maybe be percentage of time, since you can have skills lasting vastly different times

**Comment by panthernet** [comment]
@badjer2 some weirdo error with key list, try deleting the key sets and restart an app. Should be back to normal.

**Comment by badjer2** [comment]
works fine now
