### ISSUE TITLE
Any plans for gamepad support?

### ISSUE THREAD

**Issue by CODE-LA-LI-LU-LE-LO** [panthernet/D2RSO#3]
It is a very useful program, but unfortunately it cannot be used on a gamepad.
Are there any plans to provide support for gamepads?

**Comment by Icydeath** [comment]
Gamepad support would be amazing!

**Comment by Icydeath** [comment]
I figured out a way to get controller input and capture a button combo using C# dotnet 5.0 but I'm not proficient with WPF and am struggling implementing it with your code. 

I created a repo of my test application if you wanted to rip the code from it: https://github.com/Icydeath/TestGamepadInput

**Comment by panthernet** [comment]
I will take a look a bit later when I'll have some time, thanks.

**Comment by panthernet** [comment]
Okay. I have and Xbox360 gamepad so I've implemented the handler based on its response. Not sure if it will work with other gamepad so it's experimental for now and will be available in v1.0.2.

Gamepad buttons: Buttons0 - Buttons9
