### ISSUE TITLE
Add per Character settings (profiles)

### ISSUE THREAD

**Issue by spowney** [panthernet/D2RSO#4]
Useful feature request - add profiles for different characters.

eg: Sorc might use Skill Key 1 for frozen armour but Paladin might use the same key for Holy Shield.

Switching profiles would allow the same keys to be set for different skills for a seamless usage between different classes and characters.

**Comment by panthernet** [comment]
Thanks. it is probably quite a lot of work. Will take a look when I'll have some time.

**Comment by panthernet** [comment]
Implemented in v1.0.3
