### ISSUE TITLE
Add compatibility with 'quick cast'

### ISSUE THREAD

**Issue by spowney** [panthernet/D2RSO#6]
Quick cast addition to D2R allows a single button or key casting of skills.

So current settings of Select Key + Skill Key do not apply nor do they work correctly when used in conjunction with quick cast.

A quick cast option within the tool would allow for the triggering of the countdown with a single key/button press.

**Comment by panthernet** [comment]
You can set Select key with an empty value so it will be skipped. In this case the Skill key will trigger right away.
