### ISSUE TITLE
Digit keys not being detected

### ISSUE THREAD

**Issue by Firaa05** [panthernet/D2RSO#7]
When using this application, all inputs, whether they are function keys or numpad keys, are being detected. The exception is digit keys, which are not functioning. When assigning skills to be detected with 1, 2, 3, 4, 5, 6, 7, 8, 9, and 0, the input is not being detected. Control, Alt, and Shift also seem to be not functioning.

**Comment by panthernet** [comment]
Thanks, will take a look.

**Comment by panthernet** [comment]
Okay, found problem with digits. Will fix it in v1.0.2.
