### ISSUE TITLE
TO run this application, you must install .NET

### ISSUE THREAD

**Issue by badjer2** [panthernet/D2RSO#8]
But i already do have newest .NET installed

**Comment by badjer2** [comment]
saying yes to download it does nothing

**Comment by panthernet** [comment]
As I remember it requires .NET 5. Try downloading it from Microsoft web site. The latest. Net might not be enough.

**Comment by badjer2** [comment]
That did it, thanks.

**Comment by doomhound188** [comment]
Requires SDK not Desktop Runtime
