### ISSUE TITLE
Additional mouse buttons?

### ISSUE THREAD

**Issue by badjer2** [panthernet/D2RSO#9]
Could it be possible to add option for additional mouse buttons? i hae hydreas bound to F  *and* mouse 4, and i use mainly mouse4 to cast them

**Comment by panthernet** [comment]
I tried to fetch as much buttons as I can with my mouse and very scarce info on the web about thje mouse hook. Added MOUSE3 and two more buttons named MOUSEX1 and MOUSEX2. Not sure if one of them is M4, please check.

https://github.com/panthernet/D2RSO/releases/tag/1.0.4

**Comment by badjer2** [comment]
Sorry for late reply, mouse x1 and x2 are mouse buttons 4 and 5

**Comment by badjer2** [comment]
Rather mouse x2 is mouse4 i think(back button by default on my mouse)
